[book]
authors = ["Mohammed Alyousef", "Flatig L"]
language = "zh-CN"
src = "src"
title = "fltk book"

[rust]
edition = "2018"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/Flatigers/fltk-book-zh"
edit-url-template = "https://github.com/Flatigers/fltk-book-zh/edit/main/{path}"


[output.html.fold]
enable = true
level = 1
